[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."stage-image"]
  timeout = 26

[functions."stage-image-start"]
  timeout = 26

[functions."stage-replicate"]
  timeout = 26

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[context.production.environment]
  NODE_VERSION = "18"
